# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "deps(npm):"
    groups:
      typescript:
        patterns:
          - "typescript"
          - "typedoc"
          - "@types/node"
      lint:
        patterns:
          - "@types/eslint__js"
          - "@eslint/*"
          - "@stylistic/eslint-plugin"
          - "eslint*"
          - "publint"
          - "typescript-eslint"
      vite:
        patterns:
          - "vite"
          - "vite-plugin-*"
          - "vitest"
          - "@vitest/*"
    open-pull-requests-limit: 10

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "deps(gha):"
    open-pull-requests-limit: 10
